language: python
sudo: required
python:
  # - "2.6"
  - "2.7"
  # - "3.2"
  # - "3.3"
  # - "3.4"
  # - "3.5"
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo usermod -a -G audio travis
  - sudo apt-get install -y portaudio19-dev
  - sudo apt-get install -y libasound2-dev alsa-utils alsa-oss
  - sudo bash test/prep-dummy-soundcard.sh

install: 
  - pip install -r requirements.txt
  - pip install coveralls

env:
  global:
    AUDIODEV=null


# command to run tests
script:
  - type nosetests
  - sudo -E sudo -u $USER -E bash -c 'type nosetests'
  - sudo -E sudo -u $USER -E bash -c 'aplay -l'
  - sudo -E sudo -u $USER -E bash -c "source ~/virtualenv/python2.7/bin/activate; nosetests --with-coverage --cover-package=Qsorder"

after_success:
    - coveralls
