language: python
sudo: required
python:
  # - "2.6"
  # - "2.7"
  # - "3.2"
  # - "3.3"
  # - "3.4"
  - "3.5"
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo usermod -a -G audio travis
  - sudo apt-get install -y portaudio19-dev
  - sudo apt-get install -y libasound2-dev alsa-utils alsa-oss
  - sudo bash test/prep-dummy-soundcard.sh
  - sudo apt-get install -y lame
  # - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

install: 
  - pip install -r requirements.txt
  - pip install coveralls

env:
  global:
    AUDIODEV=null

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# command to run tests
script:
  - sudo -E su $USER -c "source $VIRTUAL_ENV/bin/activate; nosetests --with-coverage --cover-package=Qsorder"
  
after_success:
    - coveralls
