language: python
sudo: required
python:
  # - "2.6"
  # - "2.7"
  # - "3.2"
  # - "3.3"
  # - "3.4"
  - "3.6"
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo usermod -a -G audio travis
  - sudo apt-get install -y portaudio19-dev python-pyaudio python3-pyaudio
  - sudo apt-get install -y libasound2-dev jackd2 libjack-jackd2-0
#   - sudo bash test/prep-dummy-soundcard.sh
  - sudo apt-get install -y lame

install: 
  - pip install -r requirements.txt
  - pip install coveralls

env:
  global:
    AUDIODEV=null

# command to run tests
script:
  - sudo -E su $USER -c "source $VIRTUAL_ENV/bin/activate; nosetests --with-coverage --cover-package=Qsorder"
  
after_success:
    - coveralls
