language: python
sudo: required
python:
- '3.8'
before_install:
- sudo apt-get update -qq
- sudo usermod -a -G audio travis
- sudo apt-get install -y portaudio19-dev
- sudo apt-get install -y libasound2-dev alsa-utils alsa-oss
- sudo apt-get install linux-modules-extra-$(uname -r)
- sudo bash test/prep-dummy-soundcard.sh
- sudo apt-get install -y lame
- sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0
- sudo apt-get install -y herbstluftwm
install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - pip3 install coveralls
env:
  global: AUDIODEV=null
services:
  - xvfb
script:
- sudo -E su $USER -c "source $VIRTUAL_ENV/bin/activate; nosetests --with-coverage
  --cover-package=pyQsorder"
after_success:
- coveralls
