language: python
sudo: required
python:
  # - "2.6"
  - "2.7"
  # - "3.2"
  # - "3.3"
  # - "3.4"
  # - "3.5"
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo modprobe snd-dummy
  - sudo apt-get install -y portaudio19-dev
install: 
  - pip install -r requirements.txt
  - pip install coveralls

env:
  global:
    AUDIODEV=null


# command to run tests
script: 
   - nosetests --with-coverage --cover-package=Qsorder

after_success:
    - coveralls