# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qsorder.ui'
#
# Created: Sat Mar 12 16:45:24 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(630, 356)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 621, 351))
        self.tabWidget.setStyleSheet("background-color: rgb(243, 239, 222);")
        self.tabWidget.setObjectName("tabWidget")
        self.console_tab = QtGui.QWidget()
        self.console_tab.setObjectName("console_tab")
        self.console = QtGui.QPlainTextEdit(self.console_tab)
        self.console.setGeometry(QtCore.QRect(0, 0, 651, 321))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.console.setFont(font)
        self.console.setStyleSheet("border: 0px;")
        self.console.setTabChangesFocus(False)
        self.console.setReadOnly(True)
        self.console.setBackgroundVisible(False)
        self.console.setCenterOnScroll(False)
        self.console.setObjectName("console")
        self.tabWidget.addTab(self.console_tab, "")
        self.config_tab = QtGui.QWidget()
        self.config_tab.setObjectName("config_tab")
        self.debug = QtGui.QCheckBox(self.config_tab)
        self.debug.setGeometry(QtCore.QRect(30, 210, 70, 17))
        self.debug.setObjectName("debug")
        self.label_2 = QtGui.QLabel(self.config_tab)
        self.label_2.setGeometry(QtCore.QRect(180, 10, 263, 18))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.continuous = QtGui.QCheckBox(self.config_tab)
        self.continuous.setGeometry(QtCore.QRect(30, 240, 124, 17))
        self.continuous.setObjectName("continuous")
        self.so2r = QtGui.QCheckBox(self.config_tab)
        self.so2r.setGeometry(QtCore.QRect(30, 270, 70, 17))
        self.so2r.setObjectName("so2r")
        self.inputs = QtGui.QComboBox(self.config_tab)
        self.inputs.setGeometry(QtCore.QRect(85, 120, 191, 20))
        self.inputs.setObjectName("inputs")
        self.label_11 = QtGui.QLabel(self.config_tab)
        self.label_11.setGeometry(QtCore.QRect(20, 120, 60, 16))
        self.label_11.setObjectName("label_11")
        self.saveButton = QtGui.QPushButton(self.config_tab)
        self.saveButton.setGeometry(QtCore.QRect(400, 210, 101, 41))
        self.saveButton.setObjectName("saveButton")
        self.applyButton = QtGui.QPushButton(self.config_tab)
        self.applyButton.setGeometry(QtCore.QRect(510, 210, 101, 41))
        self.applyButton.setObjectName("applyButton")
        self.label_12 = QtGui.QLabel(self.config_tab)
        self.label_12.setGeometry(QtCore.QRect(290, 120, 102, 16))
        self.label_12.setObjectName("label_12")
        self.drop_key = QtGui.QLineEdit(self.config_tab)
        self.drop_key.setGeometry(QtCore.QRect(401, 120, 191, 20))
        self.drop_key.setObjectName("drop_key")
        self.commandLinkButton = QtGui.QCommandLinkButton(self.config_tab)
        self.commandLinkButton.setGeometry(QtCore.QRect(400, 150, 172, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.label_13 = QtGui.QLabel(self.config_tab)
        self.label_13.setGeometry(QtCore.QRect(190, 160, 131, 141))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("qsorder.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.quitButton = QtGui.QPushButton(self.config_tab)
        self.quitButton.setGeometry(QtCore.QRect(510, 270, 101, 23))
        self.quitButton.setObjectName("quitButton")
        self.layoutWidget = QtGui.QWidget(self.config_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 171, 161, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.hotkey = QtGui.QLineEdit(self.layoutWidget)
        self.hotkey.setObjectName("hotkey")
        self.horizontalLayout_3.addWidget(self.hotkey)
        self.layoutWidget1 = QtGui.QWidget(self.config_tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 50, 125, 48))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.buffer = QtGui.QSpinBox(self.layoutWidget1)
        self.buffer.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.buffer.setMaximum(1000)
        self.buffer.setProperty("value", 45)
        self.buffer.setObjectName("buffer")
        self.gridLayout.addWidget(self.buffer, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.delay = QtGui.QSpinBox(self.layoutWidget1)
        self.delay.setMaximum(1000)
        self.delay.setProperty("value", 20)
        self.delay.setObjectName("delay")
        self.gridLayout.addWidget(self.delay, 1, 1, 1, 1)
        self.layoutWidget2 = QtGui.QWidget(self.config_tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(160, 80, 431, 22))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtGui.QLabel(self.layoutWidget2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.path = QtGui.QLineEdit(self.layoutWidget2)
        self.path.setObjectName("path")
        self.horizontalLayout_2.addWidget(self.path)
        self.layoutWidget3 = QtGui.QWidget(self.config_tab)
        self.layoutWidget3.setGeometry(QtCore.QRect(160, 50, 313, 22))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtGui.QLabel(self.layoutWidget3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.port = QtGui.QSpinBox(self.layoutWidget3)
        self.port.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.port.setMinimum(1024)
        self.port.setMaximum(65535)
        self.port.setProperty("value", 12060)
        self.port.setObjectName("port")
        self.horizontalLayout.addWidget(self.port)
        self.label_10 = QtGui.QLabel(self.layoutWidget3)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.station_nr = QtGui.QSpinBox(self.layoutWidget3)
        self.station_nr.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.station_nr.setMinimum(0)
        self.station_nr.setMaximum(1024)
        self.station_nr.setProperty("value", 0)
        self.station_nr.setObjectName("station_nr")
        self.horizontalLayout.addWidget(self.station_nr)
        self.tabWidget.addTab(self.config_tab, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "QSORDER", None, QtGui.QApplication.UnicodeUTF8))
        self.console.setPlainText(QtGui.QApplication.translate("Form", "Qsorder qtGUI\n"
"K3IT\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.console_tab), QtGui.QApplication.translate("Form", "Qsorder Console", None, QtGui.QApplication.UnicodeUTF8))
        self.debug.setText(QtGui.QApplication.translate("Form", "Debug", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "QSORDER Configuration Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.continuous.setText(QtGui.QApplication.translate("Form", "Continious Recording", None, QtGui.QApplication.UnicodeUTF8))
        self.so2r.setText(QtGui.QApplication.translate("Form", "SO2R", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "Audio Input:", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("Form", "Save Config", None, QtGui.QApplication.UnicodeUTF8))
        self.applyButton.setText(QtGui.QApplication.translate("Form", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Form", "Dropbox Access Key:", None, QtGui.QApplication.UnicodeUTF8))
        self.commandLinkButton.setText(QtGui.QApplication.translate("Form", "Get Dropbox Key", None, QtGui.QApplication.UnicodeUTF8))
        self.quitButton.setText(QtGui.QApplication.translate("Form", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Hot Key: CTRL+ALT+", None, QtGui.QApplication.UnicodeUTF8))
        self.hotkey.setText(QtGui.QApplication.translate("Form", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Buffer Length:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Delay:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.path.setText(QtGui.QApplication.translate("Form", "<current directory>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "UDP Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "Station Number:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.config_tab), QtGui.QApplication.translate("Form", "Configuration", None, QtGui.QApplication.UnicodeUTF8))

# import bkg_img_rc
